### ISSUE TITLE
CtrlInventoryGrixEx hides a global script class.

### ISSUE THREAD

**Issue by LeeWannacott** [peter-kish/gloot#107]
![image](https://github.com/peter-kish/gloot/assets/49783296/3cbbd2e0-96c9-4c46-a90e-31aa8c2705c8)

After updating to GLoot - 2.3.1; I get this error. Not sure how to fix it, I tried reloading the project.

**Comment by peter-kish** [comment]
v2.3.1 includes some major refactoring, I probably should have done more thorough testing before I released it.. Anyways, I'll look into it asap.

**Comment by LeeWannacott** [comment]
I was going to try put together steps to reproduce and make an example on a new project:
![image](https://github.com/peter-kish/gloot/assets/49783296/1724def2-670d-44ef-a472-ad1aa9eccb3f)

But, uh it wont let me load a protoset for my InventoryGridStacked.

Seems like a really decent library though, just has some teething issues.

**Comment by peter-kish** [comment]
I did some refactoring/bug-fixing and I wasn't able to reproduce the issues above on the latest master version. Could you confirm this?

**Comment by LeeWannacott** [comment]
![image](https://github.com/peter-kish/gloot/assets/49783296/b97074fb-0983-40e8-90d2-cb7c6ea0b084)
![image](https://github.com/peter-kish/gloot/assets/49783296/d7489a30-69c0-47f9-9528-83a805e22c54)

I can verify it still exists for me on 2.3.2; although it might be something I have done.

**Comment by LeeWannacott** [comment]
No, it seems like the .tres do indeed exist. Basically to upgrade I delete the addons/gloot folder and paste the new one in (this time from github). Its like its not reloading the resources like maybe it caches them :thought_balloon:

**Comment by peter-kish** [comment]
Here's a wild guess:
In the screenshot I can see that `world.tscn` is selected (probably part of your project), but the code looks like GLoot code.
Could it be that some GLoot code somhow ended up in `world.tscn` as a built-in script?
If so, it would explain the `CtrlInventoryGrixEx hides a global script class` error message - it's trying to define a global class that's already defined and hides it.

**Comment by LeeWannacott** [comment]
> Here's a wild guess: In the screenshot I can see that `world.tscn` is selected (probably part of your project), but the code looks like GLoot code. Could it be that some GLoot code somhow ended up in `world.tscn` as a built-in script? If so, it would explain the `CtrlInventoryGrixEx hides a global script class` error message - it's trying to define a global class that's already defined and hides it.

Yep, I think when I delete the addons/gloot folder its deleting my world.tscn which contains linked gloot nodes in the tree hierachy (ctrlInventory stackedInventory etc...).

**Comment by LeeWannacott** [comment]
I guess to be fair it does warn me beforehand :sweat_smile: 
![image](https://github.com/peter-kish/gloot/assets/49783296/804bfb45-e161-4631-84bb-4775429d7502)

**Comment by peter-kish** [comment]
Yeah, when it comes to updating the plugin, I guess it's best to just install git and then `git pull` the latest version.
Or at least close the Godot editor and remove/copy the files from/to the file system directly.

**Comment by LeeWannacott** [comment]
Okay, I got it working although there is a couple issues, although I'm guessing they are  just to do with names of stuff changing.

**Comment by LeeWannacott** [comment]
Flag that I got the game working -minus the inventory system.

**Comment by LeeWannacott** [comment]
It doesn't even allow you to check the box in the asset installer if its already installed. So, basically you are forced to delete the nodes you are using from gloot each time you want to update gloot which isn't really ideal...

**Comment by peter-kish** [comment]
Yeah, I'm not sure if Godot has an option to update plugins from the editor. So you're probably left with copying/updating files manually from outside the editor.

But since this is a Godot thing, I'm going to close this one for now. If any other issue comes up that's probably plugin-related, feel free to open another issue.

**Comment by LeeWannacott** [comment]
>  So you're probably left with copying/updating files manually from outside the editor.

This does not work. You are literally forced to delete anything to do with gloot (which means its probably prudent to have inventory stuff as a child scene attached to some other scene) and then recreate it after updating gloot every time you want to update gloot; incredibly painful : /

> But since this is a Godot thing

Looks like it: https://github.com/godotengine/godot-proposals/issues/2262
